### ISSUE TITLE
Libre - Cheeseando a Juan

### ISSUE THREAD

**Issue by MiguelCGa** [Proyectos1-FDI-UCM/c2022-Grupo01#12]
### Descripción

El jugador es capaz de quedarse moviendo hacia un límite de una plataforma, rodar cuando se acerque Juan y pegarle sin haber recibido daño.

### Pasos

1. Moverse hacia un límite
2. Rodar cuando se acerque Juan
3. Pegar a melé  sin preocuparse poder recibir daño

### Captura de pantalla o vídeo

[Cheeseando a Juan - vídeo](https://youtu.be/a-Ik2rm3M1s)

**Comment by DavidRainder** [comment]
Esto no es un bug xD

**Comment by MiguelCGa** [comment]
Lo siento, David. No se volverá a repetir.
