### ISSUE TITLE
Gancho - Gancho no vuelve correctamente en movimiento

### ISSUE THREAD

**Issue by espiridifen** [Proyectos1-FDI-UCM/c2022-Grupo01#16]
### Descripción

El flotador se queda flotando detrás del personaje si se mantiene en movimiento, imposibilitando el uso del mismo.

### Pasos

1. Lanzar el gancho
2. Tan pronto como se pueda, empezar a moverse en cualquier dirección
3. El gancho no será recogido hasta que el jugador se vuelva a quedar quieto

### Captura de pantalla o vídeo
[Enlace al vídeo](https://youtu.be/ueDnwuLK29M)

**Comment by DavidRainder** [comment]
Está hecho de esta forma a propósito. No es un bug
