### ISSUE TITLE
Gancho - Invulnerabilidad del gancho

### ISSUE THREAD

**Issue by luisja30** [Proyectos1-FDI-UCM/c2022-Grupo01#18]
### Descripción

Según la descripción del informe de pruebas, a la hora de estar desplazándote con el gancho cuando ya se ha enganchado a un poste, deberías ser invulnerable y no recibir daño hasta que el jugador llega al poste destino. Sin embargo, hay una parte de una sala de lo que parece ser un mini jefe que si te hace daño.

### Pasos 

Paso 1.  Vamos a la zona o escena donde se encuentra esta miniboss fight (aparece en el video del enlace), que consta de una especie de zonas vacías o negras que nos hacen daño.
Paso 2. Intentamos utilizar el gancho contra uno de los postes.
Paso 3. Al ir hacia el poste indicado, vemos como una zona negra nos quita 10 puntos de hidratación mientras nos desplazamos con el gancho.

### Captura de pantalla o vídeo

[![Zona mortal con gancho]](https://youtu.be/L1DzRBatmNE)

**Comment by DavidRainder** [comment]
Esto es un bug visual que había en esta zona. La zona negra que mencionas realmente son pinchos que seguimos sin entender por qué no se veían xd. Ahora mismo ya está solucionado :)
