### ISSUE TITLE
Vacíos - Lugares vacíos que desaparecen

### ISSUE THREAD

**Issue by luisja30** [Proyectos1-FDI-UCM/c2022-Grupo01#19]
### Descripción

A la hora de coger el item de la bayeta, los lugares vacíos desaparecen y reaparecen cuando vuelves a coger otra bayeta. (Aunque creo que solo pasa en la escena de pruebas del Gancho creo)

### Pasos 

Paso 1. Coger la bayeta (Nos encontramos en la zona de pruebas del gancho).
Paso 2. Desaparecen los lugares vacíos, pero siguen ahí, aunque no se vean.
Paso 3. Si cogemos la bayeta de nuevo, reaparecen.

### Captura de pantalla o vídeo

[Vacíos invisibles :0](https://youtu.be/Sz5DZiXltGo)

**Comment by almasso** [comment]
Este bug simplemente es de la sala de pruebas y no está en el juego normal. Al crear la sala de pruebas no modificamos bien el _order in layer_, por lo que ocurre este bug visual. Es por ello que no lo consideramos como tal un bug y por ello no vamos a trabajar en él, debido a que las salas de prueba no van a estar en la versión final del juego.
