### ISSUE TITLE
Gancho - Invencible en el poste

### ISSUE THREAD

**Issue by MiguelCGa** [Proyectos1-FDI-UCM/c2022-Grupo01#2]
### Descripción

El jugador se puede quedar enganchado a un poste todo el tiempo que quiera siendo invulnerable al daño.

### Pasos

Detallar los pasos seguidos para poder reproducir el error. Si no se ha podido reproducir, entonces indicarlo igualmente.
1. Lanzar el gancho a un poste o moverse hasta uno
2. Quedarse en ese sitio y lanzar el gancho contra ese mismo poste
3. Mantener el botón de gancho pulsado
 
### Captura de pantalla o vídeo
[Invencible en el poste - vídeo](https://youtu.be/ByGgZ-KHj6E)

**Comment by almasso** [comment]
Debería estar arreglado para la versión final.
