### ISSUE TITLE
Libre - IA de cuerpo a cuerpo no es capaz de atravesar o evitar al invocador

### ISSUE THREAD

**Issue by DDiegoP** [Proyectos1-FDI-UCM/c2022-Grupo01#24]
## Descripción
Tanto los enemigos cuerpo a cuerpo normales como los invocados no son capaz de evitar quedarse atascados en el invocador

## Pasos 

1. Encontrar un invocador
2. Esperar a que invoque enemigos o atraer a un enemigo cuerpo a cuerpo normal
3. Ponerse en una posición en la que no exista una ruta directa entre el jugador y el enemigo cuerpo a cuerpo sin pasar por el invocador

https://user-images.githubusercontent.com/95857593/165848340-b3a2545f-cc99-42dc-912c-5f9fd29d1972.mp4

**Comment by almasso** [comment]
Arreglado, los enemigos que generaba el necromancer se generaban en su misma posición y se empujaban todo el rato hacia arriba.
