### ISSUE TITLE
Libre - Velocidad de disparo enemigo depende de la posición del jugador

### ISSUE THREAD

**Issue by DDiegoP** [Proyectos1-FDI-UCM/c2022-Grupo01#29]
## Descripción
La velocidad del disparo del enemigo de la sala mostrada en el video varia según la distancia del jugador.
## Pasos

1. Ir a la sala del video
2. Comprobar la velocidad del disparo del enemigo dependiendo de la distancia

https://user-images.githubusercontent.com/95857593/165919225-2b148641-c327-41fa-9c65-8eb66a4d1a98.mp4

**Comment by almasso** [comment]
Efectivamente, tenemos todos los prefabs de los enemigos de rango desactualizados. Ya hemos solucionado el error.
