### ISSUE TITLE
Enemigos - Balas flotadoras

### ISSUE THREAD

**Issue by luisja30** [Proyectos1-FDI-UCM/c2022-Grupo01#31]
### Descripción

Hay una sala (está especificada en el vídeo) en la que hay enemigos verdes (de rango) que dispara unas balas que van demasiado lentas y se quedan flotando en el aire.

### Pasos 

Paso 1. Nos ubicamos en la sala que especificada en el enlace del vídeo.
Paso 2. Nos acercamos a los enemigos de rango para que procedan a dispararnos.
Paso 3. Vemos que sus balas van muy lentas y parece que se quedan flotando.

### Captura de pantalla o vídeo

[Balas flotadoras](https://youtu.be/64dvCY9XMWQ)

**Comment by almasso** [comment]
Debería ser el mismo bug [que el que reportó Diego](https://github.com/Proyectos1-FDI-UCM/c2022-Grupo01/issues/29), por tanto ya debería estar resuelto.

**Comment by luisja30** [comment]
Okey, no lo sabia y lo puse sin querer. Perdona por duplicar issues.

**Comment by almasso** [comment]
Sin problema
