### ISSUE TITLE
Enemigos- Balas

### ISSUE THREAD

**Issue by luisja30** [Proyectos1-FDI-UCM/c2022-Grupo01#32]
### Descripción

Hay una sala (está especificada en el vídeo) en la que hay enemigos verdes (de rango) que dispara unas balas que van demasiado lentas y se quedan flotando en el aire.

### Pasos 

Paso 1. Nos ubicamos en la sala que especificada en el enlace del vídeo.
Paso 2. Nos acercamos a los enemigos de rango para que procedan a dispararnos.
Paso 3. Vemos que sus balas van muy lentas y parece que se quedan flotando.

### Captura de pantalla o vídeo

[Balas invisibles](https://youtu.be/64dvCY9XMWQ)

**Comment by IAymat** [comment]
Se trata del mismo error que ya había [reportado Diego](https://github.com/Proyectos1-FDI-UCM/c2022-Grupo01/issues/29) y después ... [tú mismo](https://github.com/Proyectos1-FDI-UCM/c2022-Grupo01/issues/31) hace 3 días xd

Duplicate of #29
Duplicate of #31
